#ifndef MONITORING_SYSTEM_OF_WATER_LEVEL_H_INCLUDED
#define MONITORING_SYSTEM_OF_WATER_LEVEL_H_INCLUDED

void USARTInit(uint16_t );
char USARTReadChar();
void USARTWriteChar(char );

#endif //  MONITORING_SYSTEM_OF_WATER_LEVEL_H_INCLUDED
